# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('text', models.TextField(blank=True, null=True)),
                ('letter', models.TextField(blank=True, null=True)),
                ('summarization', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_website',
            },
        ),
    ]
